[project]
name = "nova-proj"
revision = "1.0"
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
BARENTSWATCH_API_TOKEN = {description = "Clef d'API utilisée pour l'émetteur de trames norvégiennes."}

[profiles.development]
BARENTSWATCH_API_TOKEN = {description = "Clef d'API utilisée pour l'émetteur de trames norvégiennes."}
